EN = {
 "cover": {
  "eyebrow": "FOR PATIENTS, FAMILIES AND THE THERAPISTS WHO TREAT THEM",
  "title": "Massage, orthotherapy<br>and type 1 diabetes",
  "sub": "What hands-on therapy can and can&rsquo;t do for someone with type 1, the few things that change on the table, and what to tell the therapist before the first session.",
  "footer": "Education, not medical advice. Insulin timing and site decisions belong with your diabetes team.",
  "note": "Open with the reassurance: most people with type 1 can book a massage like anyone else. This deck is about the handful of things that are different &mdash; mainly insulin, sensors and feet &mdash; not a list of reasons to stay away.",
 },
 "who": {
  "h": "Who does what in Qu&eacute;bec",
  "lede": "Four titles you&rsquo;ll see on clinic doors. Only one of them belongs to a professional order today.",
  "cards": [
   ("white", "Massage therapist", "Therapeutic massage. <b>Not regulated</b> in Qu&eacute;bec: no professional order, and the title isn&rsquo;t protected. Standards come from the association the therapist belongs to."),
   ("white", "Orthotherapist", "Massage plus movement therapy for muscle pain and joint stiffness &mdash; a specialisation after massage training, roughly 1,000 to 1,300 hours in all depending on the school. <b>Also not regulated.</b>"),
   ("white", "Kinesiologist", "Exercise as treatment. Represented by a federation (FKQ). Qu&eacute;bec announced in June 2026 that kinesiology will join an order; that isn&rsquo;t in force yet."),
   ("teal", "Physiotherapist", "<b>Regulated</b> by the OPPQ, with a public directory. The first call for an injury, a frozen shoulder, or anything that needs a diagnosis."),
  ],
  "footer": "Sources: OQLF Grand dictionnaire terminologique &middot; Mon R&eacute;seau Plus &middot; RITMA &middot; Gouvernement du Qu&eacute;bec, 16 June 2026 &middot; OPPQ. Ontario and BC regulate massage therapists; Qu&eacute;bec does not.",
  "note": "In Qu&eacute;bec a kin&eacute;sith&eacute;rapeute is an unregulated movement therapist, not the regulated French masseur-kin&eacute;sith&eacute;rapeute. People who have lived in France mix these up.",
 },
 "why": {
  "h": "Why people with type 1 end up on the table",
  "big": "of 1,217 adults in the DCCT/EDIC study &mdash; on average 31 years with type 1 &mdash; had at least one hand or shoulder condition.",
  "bigsmall": "These people were diagnosed decades ago; how common this is with today&rsquo;s care isn&rsquo;t known yet.",
  "side": [
   ("Frozen shoulder &mdash; 31%", "A painful shoulder that slowly stiffens. About five times more likely with diabetes than without."),
   ("Carpal tunnel &mdash; 30%", "Numb, tingling fingers, often at night."),
   ("Trigger finger &mdash; 28%", "A finger that catches or locks when it bends."),
   ("Stiff hands &mdash; 22%", "Can&rsquo;t press the palms flat together (the &ldquo;prayer sign&rdquo;). Dupuytren&rsquo;s contracture: 9%."),
  ],
  "footer": "Sources: Larkin et al., Diabetes Care 2014 (DCCT/EDIC) &middot; Zreik et al. 2016. Leading explanation: glucose slowly stiffening collagen (glycation) &mdash; years of exposure, not a verdict on effort.",
  "note": "These are common, under-recognised and treatable; many people assume a stiff shoulder is just age. Intensive versus conventional treatment in the original trial: 64% versus 68%, not a significant difference. This is not a scorecard.",
 },
 "honest": {
  "h": "What massage can honestly claim",
  "cards": [
   ("teal", "Reasonably supported", ["Feeling calmer. A meta-analysis of 37 trials found single sessions lowered anxiety, blood pressure and heart rate.", "For frozen shoulder in diabetes, joint mobilisation plus exercise had the largest effect across 8 trials &mdash; though the evidence is low quality."]),
   ("white", "Disputed", ["&ldquo;Lowers stress hormones.&rdquo; One review reported cortisol falling by about a third; a stricter meta-analysis found the effect indistinguishable from zero.", "And stress itself moves blood sugar differently in different people &mdash; up, down, or not at all."]),
   ("red", "Not shown", ["Treating diabetes. Small studies saw glucose fall after sessions, most likely because massage speeds insulin absorption &mdash; a reason to check, not a therapy.", "Preventing complications by &ldquo;improving circulation&rdquo;. No good evidence, and no guideline lists it."]),
  ],
  "footer": "Sources: Moyer 2004 and 2011 &middot; Field 2005 &middot; Alsubheen 2019 &middot; Ezzo 2001 &middot; Sajedi 2011 &middot; Wiesli 2005. Evidence for every glucose claim is low: small, short, mostly uncontrolled studies.",
  "note": "This slide exists because the claims circulating online &mdash; lowers cortisol, improves circulation, helps manage glucose &mdash; are stronger than the research. Say it plainly: go because it feels good and helps you move, not to treat diabetes.",
 },
 "insulin": {
  "h": "Insulin moves faster under a working hand",
  "lede": "Rubbing, heating or working the muscle under a recent injection gets insulin into the blood faster. This has been measured since the late 1970s.",
  "big": "faster insulin absorption when an injection site was massaged for 30 minutes &mdash; and blood sugar fell faster too.",
  "bigsmall": "9 volunteers, older human insulin (Linde 1986).",
  "c2": ("Heat does it too", "Two sauna sessions raised absorption by 110% and left blood sugar 3.0 to 3.3 mmol/L lower. Hot stones, heat packs and hot tubs work the same way."),
  "c3": ("So does the muscle underneath", "Leg exercise after a leg injection raised absorption by 135% in the first ten minutes."),
  "c4": ("What to do", "Don&rsquo;t inject into an area about to be worked on. Ask the therapist to skip recent injection sites and your pump site, and no heat there."),
  "footer": "Sources: Linde 1986 &middot; Koivisto 1980 &middot; Koivisto &amp; Felig 1978 &middot; FIT Canada 2020. All small studies on older insulins; for rapid-acting analogues and pump sites the effect is inferred from heat studies (Raz 2009, Landau 2014).",
  "note": "FIT Canada: massaging the injection site immediately before or after an injection is not recommended, because it makes insulin action unpredictable. How long to keep clear depends on the insulin; your team can tell you how long yours stays active.",
 },
 "lows": {
  "h": "Lows on the table",
  "lede": "Lying still, relaxed, eyes closed, face in a cradle: the early signs of a low are easy to miss &mdash; or to mistake for relaxation.",
  "cards": [
   ("panel", "Before", "Check. If you&rsquo;re low or heading down, treat it and wait, or move the appointment. Eat as usual &mdash; don&rsquo;t arrive on an empty stomach."),
   ("panel", "Within reach", "Fast sugar on the table edge or in your hand, not in a bag across the room. Agree on one word that means &ldquo;stop, I need sugar&rdquo;."),
   ("panel", "After", "Check again before you drive. Diab&egrave;te Qu&eacute;bec warns of unexpected drops; the FQM suggests checking before and after at least the first two or three sessions."),
   ("red", "If it happens", "Stop. Sit up slowly. 15 g of fast sugar, recheck in 15 minutes. Unconscious or seizing: 911, nothing by mouth."),
  ],
  "footer": "Sources: Diab&egrave;te Qu&eacute;bec, &laquo; Spa, sauna et massoth&eacute;rapie &raquo; &middot; FQM, &laquo; Masser une personne diab&eacute;tique &raquo; &middot; Diabetes Canada. No study has looked at lows during massage directly: this is precaution, not data.",
  "note": "The one word matters. Many people with type 1 won&rsquo;t interrupt a session they are paying for. Give them permission in advance.",
 },
 "sensors": {
  "h": "Your sensor and pump on the table",
  "cards": [
   ("red", "Compression lows", "Pressure on a CGM sensor &mdash; lying on it, or a hand on it &mdash; can show a sudden low that isn&rsquo;t real. Confirm a surprising number with a finger prick before acting on it."),
   ("white", "Oils and lotions", "Dexcom and Abbott both warn against lotion near the sensor: the adhesive stops holding. The same logic applies to pump sites. Ask for a hand&rsquo;s width of clear, oil-free skin."),
   ("white", "Show where they are", "Point out your sensor and infusion set before you lie down. Draping, stretching and friction near them are how they get pulled off."),
   ("teal", "Pumps", "Keep the pump where you can reach it. If you disconnect for the session, agree with your team how long is fine &mdash; and reconnect before you leave."),
  ],
  "footer": "Sources: Mensh et al., J Diabetes Sci Technol 2013 &middot; Dexcom G7 user guide &middot; Abbott FreeStyle Libre 2 adhesion guide &middot; Medtronic Guardian 4 user guide. Oils on pump sets: our extension of the lotion warnings.",
  "note": "&ldquo;Compression low&rdquo; is the community name; the literature calls it pressure-induced sensor attenuation. Every manual says to check with a meter whenever the reading doesn&rsquo;t match how you feel.",
 },
 "notoday": {
  "h": "When to move the appointment",
  "cards": [
   ("Ketones raised", "Blood ketones 0.6 or above, or high and unwell. That&rsquo;s your sick-day plan, not a massage."),
   ("A severe low in the last 24 hours", "One that needed someone else&rsquo;s help. Your defences are blunted for the next one."),
   ("Wounds or infection", "An open sore, ulcer, blister or infection in the area to be treated &mdash; especially on the feet."),
   ("Fever or acute illness", "Sick days come first. Book again when you&rsquo;re back to your usual numbers."),
  ],
  "statement": "Everything else &mdash; newly diagnosed, pump or injections, existing complications &mdash; is a reason to tell the therapist, not a reason to stay home.",
  "footer": "Sources: FQM 2018 &middot; Diab&egrave;te Qu&eacute;bec 2014. Postponing for ketones or a recent severe low is clinical common sense rather than a published massage rule.",
  "note": "The draft advice circulating online calls for a doctor&rsquo;s clearance before every booking. The FQM asks for one only when in doubt. Don&rsquo;t medicalise a massage.",
 },
 "nerves": {
  "h": "If your feet or hands have lost feeling",
  "lede": "Neuropathy removes the one safety signal massage relies on: you saying &ldquo;that&rsquo;s too much&rdquo;. So the therapist has to judge for you.",
  "cards": [
   ("panel", "Broad pressure", "On numb areas, ask for broad, full-hand pressure rather than deep point work or aggressive stretching."),
   ("panel", "No heat on numb skin", "Hot stones, heat packs and hot towels can burn skin that can&rsquo;t feel them. Diabetes Canada already says to test bath water by hand."),
   ("panel", "Look afterwards", "The same foot check you already do daily, done again after the session: redness, blisters, broken skin."),
   ("teal", "A small signal of benefit", "Two weeks of Thai foot massage improved balance and sensation tests in 60 people with type 2 and neuropathy. Small, short, type 2 &mdash; but encouraging."),
  ],
  "footer": "Sources: Embil et al., Diabetes Canada foot care chapter 2018 &middot; Chatchawan et al. 2015 &middot; FQM 2007.",
  "note": "Tell the therapist where the numbness starts and stops. A map is more useful than the word &ldquo;neuropathy&rdquo;.",
 },
 "joints": {
  "h": "Stiff shoulders and hands: who to see",
  "cards": [
   ("white", "Get a diagnosis first", "A shoulder that stiffens over weeks, a finger that catches, numb fingers at night: see your doctor or a physiotherapist, not only a massage therapist."),
   ("teal", "What has the most support", "Joint mobilisation plus exercise, from a physiotherapist or trained therapist. Largest effect in diabetes trials &mdash; low-quality evidence. Recovery tends to be slower with diabetes."),
   ("white", "Where massage fits", "Alongside, for muscle tension and comfort. Gentle range-of-motion work matters more than force."),
   ("white", "If you&rsquo;re offered a steroid injection", "It can raise blood sugar for a while afterwards. Plan the days that follow with your diabetes team."),
  ],
  "footer": "Sources: Alsubheen et al., Arch Phys Med Rehabil 2019 (8 trials) &middot; Tang &amp; Tan 2024 &middot; Larkin et al. 2014. See also the Medications section on steroids.",
  "note": "Orthotherapists often see these first, because people book for &ldquo;a stiff shoulder&rdquo;. The most useful thing a therapist can say is &ldquo;have you mentioned this to your diabetes team?&rdquo;",
 },
 "skin": {
  "h": "Lumps, skin and getting up",
  "cards": [
   ("panel", "Lumps where insulin goes", "Rubbery lumps under the skin at injection or pump sites (lipohypertrophy) affect about a third of people with type 1. A therapist may notice them first. Insulin in those spots acts unpredictably &mdash; tell your team."),
   ("panel", "Skin", "Avoid any wound, sore, blister or infection. Moisturising dry feet is fine &mdash; just not between the toes."),
   ("panel", "Getting up", "Some people with long-standing type 1 get light-headed standing up. Sit on the edge of the table for a moment, then stand slowly."),
   ("panel", "Eyes", "Recent eye surgery or advanced retinopathy? Ask your eye specialist about time spent face-down."),
  ],
  "footer": "Sources: Deng et al., J Diabetes Investig 2018 (26 studies) &middot; Diabetes Canada foot care chapter 2018 &middot; FQM 2007 intake questions.",
  "note": "Lipohypertrophy is a genuinely useful thing for a therapist to spot, and it is a site-rotation issue, not a personal failing.",
 },
 "tell": {
  "h": "What to tell the therapist",
  "left": ("Before you lie down", [
   "I have type 1 diabetes and use insulin &mdash; a pump / injections.",
   "My sensor is <u>here</u>, my pump site is <u>here</u>. No oil, pressure or stretching on them.",
   "My last insulin was at ___, in my ___. Please skip that area, and no heat there.",
   "My glucose right now is ___ and it&rsquo;s steady / rising / falling.",
   "If I say &ldquo;<b>sugar</b>&rdquo;, stop &mdash; I may be going low.",
   "Numb areas: ___. Broad pressure, no heat. Also: stiff joints, wounds, dizziness standing up.",
  ]),
  "right": ("Bring", ["Your meter or phone, and fast sugar within reach of the table.", "~small~The printable card version of this slide is in the downloads. Hand it over at the first visit."]),
  "footer": "Built from the FQM intake questions for clients with diabetes and the sensor makers&rsquo; instructions.",
  "note": "Practise saying this once at home. People skip it at the clinic because it feels like a lot to explain to a stranger. The card does the explaining.",
 },
 "therapists": {
  "h": "For massage therapists and orthotherapists",
  "cards": [
   ("panel", "Intake", ["Pump or injections; last dose and where", "Glucose now, and its direction", "Lows in the last day", "Numb areas, wounds, dizziness standing up"]),
   ("panel", "On the table", ["A hand&rsquo;s width clear around devices &mdash; no oil, no pressure", "Skip recent injection sites; no heat there", "Broad pressure on numb skin", "Their fast sugar within their reach"]),
   ("red", "Spot a low", ["Sweating, trembling, sudden restlessness, confusion, unusual quiet.", "Stop. Sit them up slowly. Sugar first, questions after.", "Unconscious or seizing: 911. Nothing by mouth."]),
  ],
  "footer": "Sources: FQM, &laquo; Masser une personne diab&eacute;tique &raquo; &middot; Diab&egrave;te Qu&eacute;bec &middot; Dexcom G7 user guide &middot; Diabetes Canada.",
  "note": "A sensor alarm during a session is not an interruption to apologise for. Give the client a moment to read it.",
 },
 "choosing": {
  "h": "Choosing a therapist in Qu&eacute;bec",
  "cards": [
   ("white", "Check membership", "The title isn&rsquo;t protected, so the association is the check. FQM, Mon R&eacute;seau Plus and RITMA all publish member directories. Complaints go to the association."),
   ("white", "Insurance receipts", "Group plans usually require a member in good standing of an association your insurer recognises; some want a doctor&rsquo;s recommendation. Check your insurer&rsquo;s list before booking."),
   ("white", "Public coverage and taxes", "RAMQ doesn&rsquo;t cover massage or orthotherapy. In Qu&eacute;bec they don&rsquo;t count for the federal medical expense credit, and generally not the provincial one. Physiotherapy does."),
   ("teal", "One question to ask", "&ldquo;Have you worked with clients who use insulin, a pump or a sensor?&rdquo; A good answer sounds a lot like the previous slide."),
  ],
  "footer": "Sources: FQM &middot; Mon R&eacute;seau Plus (RMPQ) &middot; RITMA &middot; Desjardins group insurance claims guide &middot; Canada Revenue Agency, authorized medical practitioners list (January 2026).",
  "note": "We don&rsquo;t recommend specific clinics or associations. The point is that, in Qu&eacute;bec, the patient does the checking that an order would do elsewhere.",
 },
 "help": {
  "h": "Book it, and where to get help",
  "tiles": [
   ("#1f7a6b", "Start simple", "A relaxation massage first, so you learn how your numbers respond.", 25),
   ("#243141", "Write it down", "Glucose before and after, last dose and site. Two or three sessions show your pattern.", 25),
   ("#243141", "Diabetes Canada", "1-800-BANTING<br><span style=\"font-size:24px; color:#9fb0c0\">(1-800-226-8464)</span>", 28),
   ("#243141", "Info-Sant&eacute; (Qu&eacute;bec)", "811<br><span style=\"font-size:24px; color:#9fb0c0\">a nurse, 24/7, free</span>", 28),
   ("#c0392b", "Emergency", "911<br><span style=\"font-size:24px\">unconscious, seizing, or won&rsquo;t wake</span>", 28),
  ],
  "close": "Most people with type 1 can book a massage like anyone else. Check before and after, keep sugar within reach, show the therapist your devices &mdash; and let yourself enjoy it.",
  "footer": "Sources throughout: Diab&egrave;te Qu&eacute;bec &middot; FQM &middot; FIT Canada 2020 &middot; DCCT/EDIC &middot; Diabetes Canada &middot; device user guides. Full list on the Sources page.",
  "note": "Close on permission. The aim of this deck is that someone with type 1 books the appointment, not that they are scared out of it.",
 },
}

N = "&nbsp;"
FR = {
 "cover": {
  "eyebrow": "POUR LES PATIENTS, LES FAMILLES ET LES THÉRAPEUTES QUI LES TRAITENT",
  "title": "Massothérapie,<br>orthothérapie et diabète de type&nbsp;1",
  "sub": "Ce que la thérapie manuelle peut et ne peut pas faire avec le type&nbsp;1, les quelques choses qui changent sur la table, et quoi dire au thérapeute avant la première séance.",
  "footer": "De l'éducation, pas un avis médical. Le moment et le site d'injection se décident avec votre équipe de soins en diabète.",
  "note": "Commencez par rassurer&nbsp;: la plupart des personnes vivant avec le type&nbsp;1 peuvent réserver un massage comme tout le monde. Cette présentation porte sur les quelques éléments qui diffèrent — surtout l'insuline, les capteurs et les pieds — pas sur des raisons de s'abstenir.",
 },
 "who": {
  "h": "Qui fait quoi au Québec",
  "lede": "Quatre titres qu'on voit sur les portes des cliniques. Un seul relève aujourd'hui d'un ordre professionnel.",
  "cards": [
   ("white", "Massothérapeute", "Le massage thérapeutique. <b>Non réglementé</b> au Québec&nbsp;: aucun ordre professionnel, et le titre n'est pas protégé. Les normes viennent de l'association dont la personne est membre."),
   ("white", "Orthothérapeute", "Massothérapie et kinésithérapie pour les douleurs musculaires et la raideur articulaire — une spécialisation après la formation en massage, environ 1&nbsp;000 à 1&nbsp;300&nbsp;heures au total selon l'école. <b>Non réglementé non plus.</b>"),
   ("white", "Kinésiologue", "L'exercice comme traitement. Représenté par une fédération (FKQ). Québec a annoncé en juin 2026 l'intégration à un ordre&nbsp;; ce n'est pas encore en vigueur."),
   ("teal", "Physiothérapeute", "<b>Réglementé</b> par l'OPPQ, avec un répertoire public. Le premier choix pour une blessure, une capsulite ou tout ce qui demande un diagnostic."),
  ],
  "footer": "Sources&nbsp;: OQLF, Grand dictionnaire terminologique · Mon Réseau Plus · RITMA · Gouvernement du Québec, 16&nbsp;juin 2026 · OPPQ. L'Ontario et la C.-B. réglementent la massothérapie&nbsp;; pas le Québec.",
  "note": "Au Québec, le kinésithérapeute est un thérapeute du mouvement non réglementé, pas l'équivalent du masseur-kinésithérapeute français, qui est réglementé. Les personnes qui ont vécu en France confondent souvent les deux.",
 },
 "why": {
  "num": "66&nbsp;%",
  "h": "Pourquoi les personnes vivant avec le type&nbsp;1 consultent",
  "big": "des 1&nbsp;217 adultes de l'étude DCCT/EDIC — en moyenne 31&nbsp;ans de type&nbsp;1 — avaient au moins un problème à la main ou à l'épaule.",
  "bigsmall": "Ces personnes ont été diagnostiquées il y a des décennies&nbsp;; on ne sait pas encore à quel point c'est fréquent avec les soins d'aujourd'hui.",
  "side": [
   ("Capsulite (épaule gelée) — 31&nbsp;%", "Une épaule douloureuse qui raidit peu à peu. Environ cinq fois plus probable avec le diabète."),
   ("Syndrome du canal carpien — 30&nbsp;%", "Doigts engourdis ou qui picotent, souvent la nuit."),
   ("Doigt à ressaut — 28&nbsp;%", "Un doigt qui accroche ou se bloque en pliant."),
   ("Mains raides — 22&nbsp;%", "Impossible de joindre les paumes à plat (le «&nbsp;signe de la prière&nbsp;»). Maladie de Dupuytren&nbsp;: 9&nbsp;%."),
  ],
  "footer": "Sources&nbsp;: Larkin et coll., Diabetes Care 2014 (DCCT/EDIC) · Zreik et coll. 2016. Explication principale&nbsp;: le glucose qui rigidifie lentement le collagène (glycation) — des années d'exposition, pas un jugement sur les efforts.",
  "note": "Ces problèmes sont fréquents, sous-reconnus et traitables&nbsp;; beaucoup de gens croient qu'une épaule raide, c'est juste l'âge. Traitement intensif ou conventionnel dans l'essai d'origine&nbsp;: 64&nbsp;% contre 68&nbsp;%, une différence non significative. Ce n'est pas un bulletin.",
 },
 "honest": {
  "h": "Ce que le massage peut honnêtement promettre",
  "cards": [
   ("teal", "Assez bien appuyé", ["Se sentir plus calme. Une méta-analyse de 37&nbsp;essais&nbsp;: une séance réduit l'anxiété, la tension artérielle et la fréquence cardiaque.", "Pour la capsulite avec le diabète, la mobilisation articulaire jumelée à l'exercice a eu le plus grand effet dans 8&nbsp;essais — mais les données sont de faible qualité."]),
   ("white", "Contesté", ["«&nbsp;Fait baisser les hormones de stress.&nbsp;» Une revue rapportait une baisse du cortisol d'environ un tiers&nbsp;; une méta-analyse plus rigoureuse n'a trouvé aucun effet mesurable.", "Et le stress fait varier la glycémie différemment selon les personnes — à la hausse, à la baisse, ou pas du tout."]),
   ("red", "Non démontré", ["Traiter le diabète. De petites études ont vu la glycémie baisser après les séances, sans doute parce que le massage accélère l'absorption de l'insuline — une raison de vérifier, pas une thérapie.", "Prévenir les complications en «&nbsp;améliorant la circulation&nbsp;». Aucune donnée solide."]),
  ],
  "footer": "Sources&nbsp;: Moyer 2004 et 2011 · Field 2005 · Alsubheen 2019 · Ezzo 2001 · Sajedi 2011 · Wiesli 2005. Pour la glycémie, les données sont faibles&nbsp;: études petites, courtes, surtout sans groupe témoin.",
  "note": "Cette diapo existe parce que ce qui circule en ligne — baisse du cortisol, meilleure circulation, aide à gérer la glycémie — dépasse ce que montre la recherche. Dites-le simplement&nbsp;: on y va parce que ça fait du bien et que ça aide à bouger, pas pour traiter le diabète.",
 },
 "insulin": {
  "h": "L'insuline file plus vite sous une main qui travaille",
  "lede": "Frotter, chauffer ou faire travailler le muscle sous une injection récente fait passer l'insuline plus vite dans le sang. On le mesure depuis la fin des années&nbsp;1970.",
  "big": "absorption plus rapide de l'insuline quand le site d'injection a été massé 30&nbsp;minutes — et la glycémie a baissé plus vite.",
  "bigsmall": "9&nbsp;volontaires, ancienne insuline humaine (Linde 1986).",
  "c2": ("La chaleur aussi", "Deux séances de sauna ont augmenté l'absorption de 110&nbsp;% et abaissé la glycémie de 3,0 à 3,3&nbsp;mmol/L. Pierres chaudes, compresses et spas agissent de la même façon."),
  "c3": ("Le muscle en dessous aussi", "L'exercice des jambes après une injection dans la cuisse a augmenté l'absorption de 135&nbsp;% dans les dix premières minutes."),
  "c4": ("Quoi faire", "N'injectez pas dans une zone qui va être travaillée. Demandez d'éviter les sites d'injection récents et le site de la pompe, et pas de chaleur à ces endroits."),
  "footer": "Sources&nbsp;: Linde 1986 · Koivisto 1980 · Koivisto et Felig 1978 · FIT Canada 2020. Petites études avec d'anciennes insulines&nbsp;; pour les analogues rapides et les pompes, l'effet est déduit des études sur la chaleur (Raz 2009, Landau 2014).",
  "note": "FIT Canada&nbsp;: masser le site juste avant ou après une injection n'est pas recommandé, parce que l'action de l'insuline devient imprévisible. La durée à respecter dépend de l'insuline&nbsp;; votre équipe peut vous dire combien de temps la vôtre reste active.",
 },
 "lows": {
  "h": "L'hypo sur la table",
  "lede": "Immobile, détendu, les yeux fermés, le visage dans l'appui-tête&nbsp;: les premiers signes d'une hypo passent facilement inaperçus — ou ressemblent à de la détente.",
  "cards": [
   ("panel", "Avant", "Vérifiez. Si vous êtes bas ou en baisse, traitez et attendez, ou déplacez le rendez-vous. Mangez comme d'habitude — n'arrivez pas l'estomac vide."),
   ("panel", "À portée de main", "Du sucre rapide au bord de la table ou dans la main, pas dans un sac à l'autre bout de la pièce. Convenez d'un mot qui veut dire «&nbsp;arrêtez, j'ai besoin de sucre&nbsp;»."),
   ("panel", "Après", "Vérifiez de nouveau avant de conduire. Diabète Québec prévient des baisses inattendues&nbsp;; la FQM suggère de vérifier avant et après au moins les deux ou trois premières séances."),
   ("red", "Si ça arrive", "On arrête. On s'assoit lentement. 15&nbsp;g de sucre rapide, on revérifie après 15&nbsp;minutes. Inconscient ou en convulsion&nbsp;: 911, rien par la bouche."),
  ],
  "footer": "Sources&nbsp;: Diabète Québec, «&nbsp;Spa, sauna et massothérapie&nbsp;» · FQM, «&nbsp;Masser une personne diabétique&nbsp;» · Diabète Canada. Aucune étude n'a examiné directement l'hypo pendant un massage&nbsp;: c'est de la prudence, pas des données.",
  "note": "Le mot convenu compte. Bien des personnes vivant avec le type&nbsp;1 n'oseront pas interrompre une séance qu'elles paient. Donnez-leur la permission d'avance.",
 },
 "sensors": {
  "h": "Votre capteur et votre pompe sur la table",
  "cards": [
   ("red", "Fausses hypos par compression", "Une pression sur le capteur de glucose — couché dessus, ou une main dessus — peut afficher une baisse soudaine qui n'est pas réelle. Confirmez un chiffre surprenant au glucomètre avant d'agir."),
   ("white", "Huiles et lotions", "Dexcom et Abbott déconseillent toute lotion près du capteur&nbsp;: l'adhésif ne tient plus. Même logique pour le site de la pompe. Demandez une main de largeur de peau libre, sans huile."),
   ("white", "Montrez où ils sont", "Montrez votre capteur et votre cathéter avant de vous allonger. Les draps, les étirements et la friction sont ce qui les arrache."),
   ("teal", "Pompes", "Gardez la pompe à portée de main. Si vous la débranchez pour la séance, convenez avec votre équipe de la durée acceptable — et rebranchez-la avant de partir."),
  ],
  "footer": "Sources&nbsp;: Mensh et coll., J Diabetes Sci Technol 2013 · Guide d'utilisation Dexcom G7 · Guide d'adhérence Abbott FreeStyle Libre 2 · Guide Medtronic Guardian 4. Huiles et cathéters&nbsp;: notre extension des mises en garde sur les lotions.",
  "note": "«&nbsp;Compression low&nbsp;» est le terme courant chez les utilisateurs&nbsp;; la littérature parle d'atténuation du signal par la pression. Tous les guides disent de vérifier au glucomètre quand la lecture ne correspond pas à ce que vous ressentez.",
 },
 "notoday": {
  "h": "Quand déplacer le rendez-vous",
  "cards": [
   ("Cétones élevées", "Cétones sanguines à 0,6 ou plus, ou glycémie haute avec malaise. C'est votre plan de jours de maladie, pas un massage."),
   ("Hypo grave dans les dernières 24&nbsp;heures", "Une hypo qui a demandé l'aide de quelqu'un. Vos défenses sont affaiblies pour la suivante."),
   ("Plaie ou infection", "Plaie ouverte, ulcère, ampoule ou infection dans la zone à traiter — surtout aux pieds."),
   ("Fièvre ou maladie aiguë", "Les jours de maladie passent en premier. Réservez de nouveau une fois revenu à vos valeurs habituelles."),
  ],
  "statement": "Tout le reste — diagnostic récent, pompe ou injections, complications existantes — est une raison d'en parler au thérapeute, pas de rester à la maison.",
  "footer": "Sources&nbsp;: FQM 2018 · Diabète Québec 2014. Reporter en cas de cétones ou d'hypo grave récente relève du bon sens clinique plutôt que d'une règle publiée.",
  "note": "Certains conseils qui circulent en ligne exigent l'accord du médecin avant chaque rendez-vous. La FQM ne le demande qu'en cas de doute. Ne médicalisez pas un massage.",
 },
 "nerves": {
  "h": "Si vos pieds ou vos mains ont perdu de la sensibilité",
  "lede": "La neuropathie enlève le seul signal de sécurité sur lequel compte le massage&nbsp;: vous qui dites «&nbsp;c'est trop&nbsp;». Le thérapeute doit donc juger à votre place.",
  "cards": [
   ("panel", "Pression large", "Sur les zones engourdies, demandez une pression large, à pleine main, plutôt qu'un travail profond en points ou des étirements énergiques."),
   ("panel", "Pas de chaleur sur la peau engourdie", "Pierres chaudes, compresses et serviettes chaudes peuvent brûler une peau qui ne les sent pas. Diabète Canada conseille déjà de vérifier l'eau du bain avec la main."),
   ("panel", "Regardez après", "L'examen des pieds que vous faites déjà chaque jour, refait après la séance&nbsp;: rougeurs, ampoules, peau abîmée."),
   ("teal", "Un petit signal positif", "Deux semaines de massage thaï des pieds ont amélioré l'équilibre et la sensibilité chez 60&nbsp;personnes avec le type&nbsp;2 et une neuropathie. Petit, court, type&nbsp;2 — mais encourageant."),
  ],
  "footer": "Sources&nbsp;: Embil et coll., chapitre de Diabète Canada sur les soins des pieds 2018 · Chatchawan et coll. 2015 · FQM 2007.",
  "note": "Dites au thérapeute où l'engourdissement commence et finit. Une carte est plus utile que le mot «&nbsp;neuropathie&nbsp;».",
 },
 "joints": {
  "h": "Épaules et mains raides&nbsp;: qui consulter",
  "cards": [
   ("white", "D'abord un diagnostic", "Une épaule qui raidit sur des semaines, un doigt qui accroche, des doigts engourdis la nuit&nbsp;: voyez votre médecin ou un physiothérapeute, pas seulement un massothérapeute."),
   ("teal", "Ce qui est le mieux appuyé", "La mobilisation articulaire jumelée à l'exercice, par un physiothérapeute ou un thérapeute formé. Le plus grand effet dans les essais — données de faible qualité. La récupération est souvent plus lente avec le diabète."),
   ("white", "La place du massage", "En complément, pour la tension musculaire et le confort. Un travail doux d'amplitude compte plus que la force."),
   ("white", "Si on vous propose une infiltration", "Une injection de cortisone peut faire monter la glycémie pendant un certain temps. Planifiez les jours suivants avec votre équipe."),
  ],
  "footer": "Sources&nbsp;: Alsubheen et coll., Arch Phys Med Rehabil 2019 (8&nbsp;essais) · Tang et Tan 2024 · Larkin et coll. 2014. Voir aussi la section Médicaments sur les corticostéroïdes.",
  "note": "Les orthothérapeutes voient souvent ces problèmes en premier, parce qu'on consulte pour «&nbsp;une épaule raide&nbsp;». La phrase la plus utile d'un thérapeute&nbsp;: «&nbsp;En avez-vous parlé à votre équipe de soins en diabète&nbsp;?&nbsp;»",
 },
 "skin": {
  "h": "Bosses, peau et se relever",
  "cards": [
   ("panel", "Bosses aux sites d'insuline", "Des bosses caoutchouteuses sous la peau aux sites d'injection ou de pompe (lipohypertrophie) touchent environ le tiers des personnes avec le type&nbsp;1. Le thérapeute les remarque parfois en premier. L'insuline y agit de façon imprévisible — parlez-en à votre équipe."),
   ("panel", "Peau", "Évitez toute plaie, lésion, ampoule ou infection. Hydrater des pieds secs, c'est bien — mais pas entre les orteils."),
   ("panel", "Se relever", "Certaines personnes qui vivent avec le type&nbsp;1 depuis longtemps ont des étourdissements en se levant. Asseyez-vous un moment au bord de la table, puis levez-vous lentement."),
   ("panel", "Yeux", "Chirurgie oculaire récente ou rétinopathie avancée&nbsp;? Demandez à votre spécialiste des yeux combien de temps rester à plat ventre."),
  ],
  "footer": "Sources&nbsp;: Deng et coll., J Diabetes Investig 2018 (26&nbsp;études) · Diabète Canada, soins des pieds 2018 · FQM 2007, questionnaire d'accueil.",
  "note": "La lipohypertrophie est une chose vraiment utile à repérer pour un thérapeute, et c'est une question de rotation des sites, pas un échec personnel.",
 },
 "tell": {
  "h": "Quoi dire au thérapeute",
  "left": ("Avant de vous allonger", [
   "J'ai le diabète de type&nbsp;1 et je prends de l'insuline — pompe / injections.",
   "Mon capteur est <u>ici</u>, le site de ma pompe est <u>ici</u>. Pas d'huile, de pression ni d'étirement dessus.",
   "Ma dernière insuline&nbsp;: à ___, dans ___. Évitez cette zone, et pas de chaleur.",
   "Ma glycémie en ce moment&nbsp;: ___, stable / en hausse / en baisse.",
   "Si je dis «&nbsp;<b>sucre</b>&nbsp;», arrêtez — je fais peut-être une hypo.",
   "Zones engourdies&nbsp;: ___. Pression large, pas de chaleur. Aussi&nbsp;: articulations raides, plaies, étourdissements.",
  ]),
  "right": ("Apportez", ["Votre glucomètre ou votre téléphone, et du sucre rapide à portée de la table.", "~small~La carte imprimable de cette diapo est dans les téléchargements. Remettez-la à la première visite."]),
  "footer": "Inspiré du questionnaire d'accueil de la FQM pour la clientèle diabétique et des consignes des fabricants de capteurs.",
  "note": "Exercez-vous à le dire une fois à la maison. On saute souvent cette étape à la clinique parce que ça semble long à expliquer à un inconnu. La carte s'en charge.",
 },
 "therapists": {
  "h": "Pour les massothérapeutes et orthothérapeutes",
  "cards": [
   ("panel", "Accueil", ["Pompe ou injections&nbsp;; dernière dose et site", "Glycémie actuelle et sa tendance", "Hypos dans la dernière journée", "Zones engourdies, plaies, étourdissements"]),
   ("panel", "Sur la table", ["Une main de largeur autour des appareils — sans huile ni pression", "Éviter les sites d'injection récents&nbsp;; pas de chaleur", "Pression large sur la peau engourdie", "Son sucre rapide à sa portée"]),
   ("red", "Repérer une hypo", ["Sueurs, tremblements, agitation soudaine, confusion, silence inhabituel.", "On arrête. On l'assoit lentement. Le sucre d'abord, les questions après.", "Inconscient ou en convulsion&nbsp;: 911. Rien par la bouche."]),
  ],
  "footer": "Sources&nbsp;: FQM, «&nbsp;Masser une personne diabétique&nbsp;» · Diabète Québec · Guide Dexcom G7 · Diabète Canada.",
  "note": "Une alarme du capteur pendant la séance n'est pas une interruption dont il faut s'excuser. Laissez à la personne le temps de la lire.",
 },
 "choosing": {
  "h": "Choisir un thérapeute au Québec",
  "cards": [
   ("white", "Vérifiez l'adhésion", "Le titre n'est pas protégé&nbsp;: c'est l'association qui fait foi. La FQM, Mon Réseau Plus et RITMA publient des répertoires de membres. Les plaintes vont à l'association."),
   ("white", "Reçus d'assurance", "Les assurances collectives exigent en général un membre en règle d'une association reconnue par votre assureur&nbsp;; certaines veulent une recommandation médicale. Vérifiez la liste de votre assureur avant de réserver."),
   ("white", "RAMQ et impôts", "La RAMQ ne couvre ni la massothérapie ni l'orthothérapie. Au Québec, elles ne donnent pas droit au crédit fédéral pour frais médicaux, et en général pas au crédit provincial. La physiothérapie, oui."),
   ("teal", "Une question à poser", "«&nbsp;Avez-vous déjà traité des clients qui ont une pompe, un capteur ou de l'insuline&nbsp;?&nbsp;» Une bonne réponse ressemble beaucoup à la diapo précédente."),
  ],
  "footer": "Sources&nbsp;: FQM · Mon Réseau Plus (RMPQ) · RITMA · Guide de réclamation Desjardins Assurances · Agence du revenu du Canada, liste des praticiens autorisés (janvier 2026).",
  "note": "Nous ne recommandons ni clinique ni association en particulier. Le point&nbsp;: au Québec, c'est le patient qui fait les vérifications qu'un ordre ferait ailleurs.",
 },
 "help": {
  "h": "Réservez, et où trouver de l'aide",
  "tiles": [
   ("#1f7a6b", "Commencez simplement", "Un massage de détente d'abord, pour voir comment votre glycémie réagit.", 25),
   ("#243141", "Notez-le", "Glycémie avant et après, dernière dose et site. Deux ou trois séances montrent votre tendance.", 25),
   ("#243141", "Diabète Canada", "1-800-BANTING<br><span style=\"font-size:24px; color:#9fb0c0\">(1-800-226-8464)</span>", 28),
   ("#243141", "Info-Santé", "811<br><span style=\"font-size:24px; color:#9fb0c0\">une infirmière, 24/7, gratuit</span>", 28),
   ("#c0392b", "Urgence", "911<br><span style=\"font-size:24px\">inconscient, convulsions, ne se réveille pas</span>", 28),
  ],
  "close": "La plupart des personnes vivant avec le type&nbsp;1 peuvent réserver un massage comme tout le monde. Vérifiez avant et après, gardez du sucre à portée de main, montrez vos appareils au thérapeute — et permettez-vous d'en profiter.",
  "footer": "Sources&nbsp;: Diabète Québec · FQM · FIT Canada 2020 · DCCT/EDIC · Diabète Canada · guides des fabricants. Liste complète à la page Sources.",
  "note": "Terminez sur une permission. Le but est que la personne réserve le rendez-vous, pas qu'elle en ait peur.",
 },
}
